### ISSUE TITLE
GraphQL 404's

### ISSUE THREAD

**Issue by willisplummer** [rahenrique/rah.collectiveaccess.boilerplate#9]
I've been trying to figure out how to use the `develop` or `dev/1.8rc5` branches to try the graphql API for the past two days, and I have it all deployed and running but when I hit either `localhost:666/providence/service/Auth` or `localhost:666/service/Auth` I get a 404. Do you have any tips for getting this to work?

**Comment by rahenrique** [comment]
As far as I know, the branch that has a functioning implementation of the GraphQL API is the [dev/graphql-api](https://github.com/collectiveaccess/providence/tree/dev/graphql-api)

Have you tried changing the branch to this **dev/graphql-api**?
Like I have mentioned [here](https://github.com/rahenrique/rah.collectiveaccess.boilerplate#graphql-api-not-working), I have tested this setup a few months ago using this branch, and had some things working.

Besides that, I haven't touched the GraphQL API implementation since then... I'm still using the legacy API in my current project.

**Comment by willisplummer** [comment]
Cool - thanks for that info. I had assumed that the 1.8 release candidates or develop would all have implemented the graphql API, because it's so prominently featured in the 1.8 documentation but I don't think it's there yet haha. I'm going to stick with the legacy thing too. Appreciate the reply!
